/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Allergy } from './Allergy';
import {
    AllergyFromJSON,
    AllergyFromJSONTyped,
    AllergyToJSON,
    AllergyToJSONTyped,
} from './Allergy';

/**
 * 
 * @export
 * @interface Allergen
 */
export interface Allergen {
    /**
     * 
     * @type {number}
     * @memberof Allergen
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Allergen
     */
    name?: string;
    /**
     * 
     * @type {Allergy}
     * @memberof Allergen
     */
    allergy?: Allergy;
}

/**
 * Check if a given object implements the Allergen interface.
 */
export function instanceOfAllergen(value: object): value is Allergen {
    return true;
}

export function AllergenFromJSON(json: any): Allergen {
    return AllergenFromJSONTyped(json, false);
}

export function AllergenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Allergen {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'allergy': json['allergy'] == null ? undefined : AllergyFromJSON(json['allergy']),
    };
}

export function AllergenToJSON(json: any): Allergen {
    return AllergenToJSONTyped(json, false);
}

export function AllergenToJSONTyped(value?: Allergen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'allergy': AllergyToJSON(value['allergy']),
    };
}

