/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Authority
 */
export interface Authority {
    /**
     * 
     * @type {number}
     * @memberof Authority
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Authority
     */
    authority?: string;
}

/**
 * Check if a given object implements the Authority interface.
 */
export function instanceOfAuthority(value: object): value is Authority {
    return true;
}

export function AuthorityFromJSON(json: any): Authority {
    return AuthorityFromJSONTyped(json, false);
}

export function AuthorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authority {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'authority': json['authority'] == null ? undefined : json['authority'],
    };
}

export function AuthorityToJSON(json: any): Authority {
    return AuthorityToJSONTyped(json, false);
}

export function AuthorityToJSONTyped(value?: Authority | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'authority': value['authority'],
    };
}

