/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Menu
 */
export interface Menu {
    /**
     * 
     * @type {number}
     * @memberof Menu
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Menu
     */
    name?: string;
}

/**
 * Check if a given object implements the Menu interface.
 */
export function instanceOfMenu(value: object): value is Menu {
    return true;
}

export function MenuFromJSON(json: any): Menu {
    return MenuFromJSONTyped(json, false);
}

export function MenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): Menu {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MenuToJSON(json: any): Menu {
    return MenuToJSONTyped(json, false);
}

export function MenuToJSONTyped(value?: Menu | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

