/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { Restaurant } from './Restaurant';
import {
    RestaurantFromJSON,
    RestaurantFromJSONTyped,
    RestaurantToJSON,
    RestaurantToJSONTyped,
} from './Restaurant';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageRestaurant
 */
export interface PageRestaurant {
    /**
     * 
     * @type {number}
     * @memberof PageRestaurant
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRestaurant
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRestaurant
     */
    size?: number;
    /**
     * 
     * @type {Array<Restaurant>}
     * @memberof PageRestaurant
     */
    content?: Array<Restaurant>;
    /**
     * 
     * @type {number}
     * @memberof PageRestaurant
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageRestaurant
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {number}
     * @memberof PageRestaurant
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageRestaurant
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageRestaurant
     */
    last?: boolean;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageRestaurant
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageRestaurant
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageRestaurant interface.
 */
export function instanceOfPageRestaurant(value: object): value is PageRestaurant {
    return true;
}

export function PageRestaurantFromJSON(json: any): PageRestaurant {
    return PageRestaurantFromJSONTyped(json, false);
}

export function PageRestaurantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageRestaurant {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RestaurantFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortObjectFromJSON)),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageRestaurantToJSON(json: any): PageRestaurant {
    return PageRestaurantToJSONTyped(json, false);
}

export function PageRestaurantToJSONTyped(value?: PageRestaurant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RestaurantToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

