/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordChangeContainer
 */
export interface PasswordChangeContainer {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeContainer
     */
    oldPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeContainer
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the PasswordChangeContainer interface.
 */
export function instanceOfPasswordChangeContainer(value: object): value is PasswordChangeContainer {
    return true;
}

export function PasswordChangeContainerFromJSON(json: any): PasswordChangeContainer {
    return PasswordChangeContainerFromJSONTyped(json, false);
}

export function PasswordChangeContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordChangeContainer {
    if (json == null) {
        return json;
    }
    return {
        
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function PasswordChangeContainerToJSON(json: any): PasswordChangeContainer {
    return PasswordChangeContainerToJSONTyped(json, false);
}

export function PasswordChangeContainerToJSONTyped(value?: PasswordChangeContainer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
    };
}

