/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMetaBase } from './UserMetaBase';
import {
    UserMetaBaseFromJSON,
    UserMetaBaseFromJSONTyped,
    UserMetaBaseToJSON,
    UserMetaBaseToJSONTyped,
} from './UserMetaBase';

/**
 * 
 * @export
 * @interface UserMeta
 */
export interface UserMeta extends UserMetaBase {
}

/**
 * Check if a given object implements the UserMeta interface.
 */
export function instanceOfUserMeta(value: object): value is UserMeta {
    return true;
}

export function UserMetaFromJSON(json: any): UserMeta {
    return UserMetaFromJSONTyped(json, false);
}

export function UserMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMeta {
    return json;
}

export function UserMetaToJSON(json: any): UserMeta {
    return UserMetaToJSONTyped(json, false);
}

export function UserMetaToJSONTyped(value?: UserMeta | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

