/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageRestaurant,
  Restaurant,
} from '../models/index';

export interface GetRestaurantByIdRequest {
    id: number;
}

export interface SearchRestaurantRequest {
    keyword: string;
    page?: number;
    size?: number;
}

/**
 * 
 */
export class RestaurantControllerApi extends runtime.BaseAPI {

    /**
     */
    async getRestaurantByIdRaw(requestParameters: GetRestaurantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Restaurant>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRestaurantById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/restaurant/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getRestaurantById(requestParameters: GetRestaurantByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Restaurant> {
        const response = await this.getRestaurantByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchRestaurantRaw(requestParameters: SearchRestaurantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageRestaurant>> {
        if (requestParameters['keyword'] == null) {
            throw new runtime.RequiredError(
                'keyword',
                'Required parameter "keyword" was null or undefined when calling searchRestaurant().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchRestaurant`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async searchRestaurant(requestParameters: SearchRestaurantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageRestaurant> {
        const response = await this.searchRestaurantRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
