/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Restaurant } from './Restaurant';
import {
    RestaurantFromJSON,
    RestaurantFromJSONTyped,
    RestaurantToJSON,
    RestaurantToJSONTyped,
} from './Restaurant';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface RestaurantRating
 */
export interface RestaurantRating {
    /**
     * 
     * @type {number}
     * @memberof RestaurantRating
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RestaurantRating
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof RestaurantRating
     */
    comment?: string;
    /**
     * 
     * @type {User}
     * @memberof RestaurantRating
     */
    user?: User;
    /**
     * 
     * @type {Restaurant}
     * @memberof RestaurantRating
     */
    restaurant?: Restaurant;
}

/**
 * Check if a given object implements the RestaurantRating interface.
 */
export function instanceOfRestaurantRating(value: object): value is RestaurantRating {
    return true;
}

export function RestaurantRatingFromJSON(json: any): RestaurantRating {
    return RestaurantRatingFromJSONTyped(json, false);
}

export function RestaurantRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantRating {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'restaurant': json['restaurant'] == null ? undefined : RestaurantFromJSON(json['restaurant']),
    };
}

export function RestaurantRatingToJSON(json: any): RestaurantRating {
    return RestaurantRatingToJSONTyped(json, false);
}

export function RestaurantRatingToJSONTyped(value?: RestaurantRating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rating': value['rating'],
        'comment': value['comment'],
        'user': UserToJSON(value['user']),
        'restaurant': RestaurantToJSON(value['restaurant']),
    };
}

